<a href="https://colab.research.google.com/github/lucianoyllarreta/CLASE_CIENCIA_DATOS_I/blob/main/CLASE_CIENCIA_DATOS_I/LOS%204%20FANTASTICOS/Clase15.04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
from google.colab import files
upload  = files.upload()

Saving disuguaglianza-economica-globale-e-povert-1980-2024.csv to disuguaglianza-economica-globale-e-povert-1980-2024.csv

In [17]:
import pandas as pd
df = pd.read_csv('disuguaglianza-economica-globale-e-povert-1980-2024.csv')

In [23]:
### CLASIFICACIÓN GEOGRÁFICA DE LOS PAÍSES ###

# AMÉRICA
america_del_sur = ['Argentina', 'Bolivia', 'Brazil', 'Chile', 'Colombia', 'Ecuador', 'Guyana', 'Paraguay', 'Peru', 'Suriname', 'Uruguay', 'Venezuela']
america_central_y_caribe = ['Belize', 'Costa Rica', 'El Salvador', 'Guatemala', 'Honduras','Nicaragua', 'Panama', 'Bahamas', 'Barbados', 'Cuba', 'Dominica','Dominican Republic', 'Grenada', 'Haiti', 'Jamaica', 'Saint Kitts and Nevis','Saint Lucia', 'Saint Vincent and the Grenadines', 'Trinidad and Tobago']
america_del_norte = ['Canada', 'United States', 'Mexico']

# EUROPA
europa = ['Albania', 'Andorra', 'Austria', 'Belarus', 'Belgium', 'Bosnia and Herzegovina','Bulgaria', 'Croatia', 'Cyprus', 'Czechia', 'Denmark', 'Estonia', 'Finland','France', 'Germany', 'Greece', 'Hungary', 'Iceland', 'Ireland', 'Italy','Latvia', 'Lithuania', 'Luxembourg', 'Malta', 'Moldova', 'Montenegro','Netherlands', 'North Macedonia', 'Norway', 'Poland', 'Portugal', 'Romania','Russia', 'Serbia', 'Slovakia', 'Slovenia', 'Spain', 'Sweden', 'Switzerland','Ukraine', 'United Kingdom']

# ÁFRICA
africa = ['Algeria', 'Angola', 'Benin', 'Botswana', 'Burkina Faso', 'Burundi', 'Cabo Verde','Cameroon', 'Central African Republic', 'Chad', 'Comoros', 'Congo', 'Cote d\'Ivoire','Democratic Republic of Congo', 'Djibouti', 'Egypt', 'Equatorial Guinea', 'Eritrea','Eswatini', 'Ethiopia', 'Gabon', 'Gambia', 'Ghana', 'Guinea', 'Guinea-Bissau','Kenya', 'Lesotho', 'Liberia', 'Libya', 'Madagascar', 'Malawi', 'Mali','Mauritania', 'Mauritius', 'Morocco', 'Mozambique', 'Namibia', 'Niger','Nigeria', 'Rwanda', 'Sao Tome and Principe', 'Senegal', 'Seychelles','Sierra Leone', 'Somalia', 'South Africa', 'South Sudan', 'Sudan', 'Tanzania','Togo', 'Tunisia', 'Uganda', 'Zambia', 'Zimbabwe']

# ASIA
asia = ['Afghanistan', 'Armenia', 'Azerbaijan', 'Bahrain', 'Bangladesh', 'Bhutan','Brunei', 'Cambodia', 'China', 'Georgia', 'India', 'Indonesia', 'Iran','Iraq', 'Israel', 'Japan', 'Jordan', 'Kazakhstan', 'Kuwait', 'Kyrgyzstan','Laos', 'Lebanon', 'Malaysia', 'Maldives', 'Mongolia', 'Myanmar', 'Nepal','North Korea', 'Oman', 'Pakistan', 'Palestine', 'Philippines', 'Qatar','Saudi Arabia', 'Singapore', 'South Korea', 'Sri Lanka', 'Syria', 'Taiwan','Tajikistan', 'Thailand', 'Timor', 'Turkey', 'Turkmenistan','United Arab Emirates', 'Uzbekistan', 'Vietnam', 'Yemen']

# OCEANÍA
oceania = ['Australia', 'Fiji', 'Kiribati', 'Marshall Islands', 'Micronesia (country)','Nauru', 'New Zealand', 'Palau', 'Papua New Guinea', 'Samoa','Solomon Islands', 'Tonga', 'Tuvalu', 'Vanuatu']


### BLOQUES ECONÓMICOS ###

# MERCOSUR
mercosur = ['Argentina', 'Brazil', 'Paraguay', 'Uruguay', 'Venezuela']

# PAÍSES EMERGENTES
brics = ['Brazil', 'Russia', 'India', 'China', 'South Africa','Egypt', 'Ethiopia', 'Iran', 'United Arab Emirates']

# PETRÓLEO/ENERGÍA
medio_oriente = ['Bahrain', 'Iran', 'Iraq', 'Israel', 'Jordan', 'Kuwait', 'Lebanon','Oman', 'Palestine', 'Qatar', 'Saudi Arabia', 'Syria','United Arab Emirates', 'Yemen']

# CLUB DE PAÍSES DESARROLLADOS
ocde = ['Austria', 'Belgium', 'Canada', 'Chile', 'Colombia', 'Czechia', 'Denmark','Estonia', 'Finland', 'France', 'Germany', 'Greece', 'Hungary', 'Iceland','Ireland', 'Israel', 'Italy', 'Japan', 'South Korea', 'Latvia', 'Lithuania','Luxembourg', 'Mexico', 'Netherlands', 'New Zealand', 'Norway', 'Poland','Portugal', 'Slovakia', 'Slovenia', 'Spain', 'Sweden', 'Switzerland','Turkey', 'United Kingdom', 'United States', 'Australia']

# UNIÓN EUROPEA
union_europea = ['Austria', 'Belgium', 'Bulgaria', 'Croatia', 'Cyprus', 'Czechia', 'Denmark', 'Estonia', 'Finland', 'France', 'Germany', 'Greece', 'Hungary', 'Ireland', 'Italy', 'Latvia', 'Lithuania', 'Luxembourg', 'Malta', 'Netherlands', 'Poland', 'Portugal', 'Romania', 'Slovakia', 'Slovenia', 'Spain', 'Sweden']

In [24]:
### EUROPA ###

union_europea = ['Austria', 'Belgium', 'Bulgaria', 'Croatia', 'Cyprus', 'Czechia','Denmark', 'Estonia', 'Finland', 'France', 'Germany', 'Greece','Hungary', 'Ireland', 'Italy', 'Latvia', 'Lithuania', 'Luxembourg','Malta', 'Netherlands', 'Poland', 'Portugal', 'Romania', 'Slovakia','Slovenia', 'Spain', 'Sweden']

europa_no_ue = ['Albania', 'Andorra', 'Belarus', 'Bosnia and Herzegovina', 'Iceland','Moldova', 'Montenegro', 'North Macedonia', 'Norway', 'Russia','Serbia', 'Switzerland', 'Ukraine', 'United Kingdom']

In [18]:
print(df.columns)
display(df.head())

Index(['country', 'year', 'iso_code', 'population', 'gdp', 'gdp_per_capita',
       'poverty_rate', 'gini_index', 'income_top1', 'income_top10',
       'income_bottom50'],
      dtype='object')

,country,year,iso_code,population,gdp,gdp_per_capita,poverty_rate,gini_index,income_top1,income_top10,income_bottom50
0,Afghanistan,1980,AFG,13169313,1.532984e+10,1164.06,NaN,NaN,16.22,41.94,17.17
1,Afghanistan,1981,AFG,11937586,1.564534e+10,1310.60,NaN,NaN,16.22,41.94,17.17
2,Afghanistan,1982,AFG,10991380,1.598041e+10,1453.90,NaN,NaN,16.22,41.94,17.17
3,Afghanistan,1983,AFG,10917985,1.675533e+10,1534.65,NaN,NaN,16.22,41.94,17.17
4,Afghanistan,1984,AFG,11190222,1.707215e+10,1525.63,NaN,NaN,16.22,41.94,17.17

### Paso 1: Filtrar los últimos 20 años y asignar la región
Creamos un nuevo DataFrame con datos desde 2004 y aplicamos las listas de regiones definidas anteriormente.

In [34]:
# 1. Filtrar por año
df_20_years = df[df['year'] >= 2004].copy()

# 2. Función simple para asignar región
def definir_region(pais):
    if pais in america_del_sur: return 'América del Sur'
    if pais in america_central_y_caribe: return 'Centroamérica y Caribe'
    if pais in america_del_norte: return 'América del Norte'
    if pais in europa: return 'Europa'
    if pais in africa: return 'África'
    if pais in asia: return 'Asia'
    if pais in oceania: return 'Oceanía'


df_20_years['region'] = df_20_years['country'].apply(definir_region)

In [36]:
# 1. Filtrar por año
df_20_years2 = df[df['year'] >= 2004].copy()

# 2. Función simple para asignar región
def definir_region(pais):
    if pais in mercosur: return 'Mercosur'
    if pais in brics: return 'Brics'
    if pais in medio_oriente: return 'Medio Oriente'
    if pais in union_europea: return 'Union Europea'
    if pais in ocde: return 'OCDE'
    if pais in europa_no_ue: return 'Europa no UE'
df_20_years2['region'] = df_20_years2['country'].apply(definir_region)

In [37]:
# Agrupamos y calculamos la media
resumen_regiones = df_20_years.groupby('region')[['gdp', 'population']].mean()

display(resumen_regiones)

                                 gdp    population
region
América del Norte       6.597540e+12  1.587636e+08
América del Sur         5.451183e+11  3.366861e+07
Asia                    1.037052e+12  9.369118e+07
Centroamérica y Caribe  4.519363e+10  4.377106e+06
Europa                  5.579145e+11  1.806584e+07
Oceanía                 6.171645e+11  2.790263e+06
África                  9.958045e+10  2.259112e+07

In [38]:
resumen_bloqueseconomicos = df_20_years2.groupby('region')[['gdp', 'population']].mean()

display(resumen_bloqueseconomicos)

                        gdp    population
region
Brics          3.772681e+12  3.967516e+08
Europa no UE   1.009837e+11  8.263407e+06
Medio Oriente  2.451573e+11  1.274469e+07
Mercosur       8.132721e+11  5.605178e+07
OCDE           2.361783e+12  6.453303e+07
Union Europea  5.564286e+11  1.640538e+07

In [31]:
# Cálculo final
resumen_regiones['pbi_per_capita_promedio'] = resumen_regiones['gdp'] / resumen_regiones['population']

# Mostramos el resultado ordenado
display(resumen_regiones[['pbi_per_capita_promedio']].sort_values(by='pbi_per_capita_promedio', ascending=False))

                        pbi_per_capita_promedio
region
Oceanía                           221185.061223
América del Norte                  41555.740304
Europa                             30882.293752
América del Sur                    16190.698073
Asia                               11068.835279
Centroamérica y Caribe             10325.001436
África                              4407.947543

In [39]:

resumen_bloqueseconomicos['pbi_per_capita_promedio'] = resumen_bloqueseconomicos['gdp'] / resumen_bloqueseconomicos['population']


display(resumen_bloqueseconomicos[['pbi_per_capita_promedio']].sort_values(by='pbi_per_capita_promedio', ascending=False))

               pbi_per_capita_promedio
region
OCDE                      36598.047778
Union Europea             33917.442316
Medio Oriente             19236.039006
Mercosur                  14509.299445
Europa no UE              12220.586558
Brics                      9508.925518

In [55]:
gdppercapita_inicial = df.groupby('country')['gdp_per_capita'].first()
gdppercapita_final = df.groupby('country')['gdp_per_capita'].last()

crecimiento_pctpercapita = ((gdppercapita_final - gdppercapita_inicial) / gdppercapita_inicial) * 100

# Ranking de los países que más crecieron porcentualmente
print(crecimiento_pctpercapita.sort_values(ascending=True).head(30

                                                       ))

country
Liberia                        -80.238686
Syria                          -77.061671
Venezuela                      -66.308634
Yemen                          -54.419848
Mozambique                     -53.632813
Central African Republic       -37.780145
North Korea                    -35.356529
Burundi                        -26.015143
Haiti                          -24.271348
Niger                          -23.650219
Zimbabwe                       -23.305784
Madagascar                     -21.774771
Kyrgyzstan                     -19.768271
Democratic Republic of Congo   -13.847804
Tajikistan                     -12.973183
Sierra Leone                   -12.581374
Moldova                        -12.525961
Ukraine                        -11.209182
Palestine                       -6.429804
Djibouti                        -6.046658
Barbados                        -2.184692
Togo                            11.048058
Namibia                         11.503470
Afghanistan                     12.844699
Cote d'Ivoire                   17.528129
Sao Tome and Principe           20.158896
Iraq                            20.979346
Mali                            26.324175
Jordan                          27.590686
Malawi                          28.298500
Name: gdp_per_capita, dtype: float64

In [56]:
gdppercapita_inicial = df.groupby('country')['gdp_per_capita'].first()
gdppercapita_final = df.groupby('country')['gdp_per_capita'].last()

crecimiento_pctpercapita = ((gdppercapita_final - gdppercapita_inicial) / gdppercapita_inicial) * 100

# Ranking de los países que más crecieron porcentualmente
print(crecimiento_pctpercapita.sort_values(ascending=False).head(30

                                                       ))

country
China                 882.298919
Mongolia              740.805500
Botswana              614.089097
Laos                  589.660766
South Korea           581.032184
Vietnam               577.214473
Cape Verde            560.787688
Taiwan                546.187673
Singapore             506.832480
Bangladesh            479.522083
Bahrain               465.976664
India                 397.658498
Oman                  392.273475
Equatorial Guinea     383.095857
Turkey                355.129896
Dominican Republic    352.771985
Dominica              349.598444
Ireland               345.151816
Indonesia             325.262131
Myanmar               312.189644
Malaysia              309.310913
Egypt                 305.345974
Romania               299.955652
Seychelles            292.125483
Sri Lanka             277.167276
Thailand              273.673543
Norway                267.816746
Malta                 265.779389
Poland                250.512548
Albania               250.135488
Name: gdp_per_capita, dtype: float64

In [46]:
gdp_inicial = df.groupby('country')['gdp'].first()
gdp_final = df.groupby('country')['gdp'].last()

crecimiento_pct = ((gdp_final - gdp_inicial) / gdp_inicial) * 100

# Ranking de los países que más crecieron porcentualmente
print(crecimiento_pct.sort_values(ascending=False).head(10))

country
Qatar                   3414.082234
Equatorial Guinea       2918.468166
Bahrain                 2317.622641
Oman                    2225.663185
Botswana                1758.470365
United Arab Emirates    1664.805718
Mongolia                1573.374807
Laos                    1483.310896
Angola                  1432.818258
China                   1323.922865
Name: gdp, dtype: float64

In [ ]:
gdp_inicial = df.groupby('country')['gdp'].first()
gdp_final = df.groupby('country')['gdp'].last()

crecimiento_pct = ((gdp_final - gdp_inicial) / gdp_inicial) * 100

# Ranking de los países que más crecieron porcentualmente
print(crecimiento_pct.sort_values(ascending=False).head(10))